before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y liblapack-dev libblas-dev 

language: julia
os:
  - linux
  - windows
julia:
  - 1.1

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip